name: Test, Build, Package and Optionally Release

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:

  get-commit-sha:

    runs-on: ubuntu-latest

    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha }}

    steps:
        
      - id: short-sha
        uses: benjlevesque/short-sha@v1.2
        with:
          length: 7

  build-release:
  
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [linux, windows, freebsd]
        arch: [386, amd64]

    needs: [get-commit-sha]

    runs-on: ubuntu-latest
    
    env:
        SRCPATH: ${{ github.workspace }}/go/src/monitoring-agent-client

    steps:

      - id: install-go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
            
      - id: checkout-code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - id: upload-wix-definition-file
        if: ${{ matrix.os == 'windows' }}
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{ needs.get-commit-sha.outputs.short-sha }}-wix-wxs"
          path: "${{ env.SRCPATH }}/monitoring-agent-client.wxs"
          if-no-files-found: error
          
      - id: upload-deb-build-files
        if: ${{ matrix.os == 'linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{ needs.get-commit-sha.outputs.short-sha }}-DEBIAN"
          path: "${{ env.SRCPATH }}/DEBIAN"
          if-no-files-found: error

      - id: upload-systemd-unit-file
        if: ${{ matrix.os == 'linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{ needs.get-commit-sha.outputs.short-sha }}-systemd-unit-file"
          path: "${{ env.SRCPATH }}/monitoring-agent-client.service"
          if-no-files-found: error

      - id: dependencies-and-build
        run: |
          os=${{ matrix.os }}
          arch=${{ matrix.arch }}
          goversion=${{ matrix.go-version }}
          echo "Building $os-$arch-$goversion"
          
          suffix=$([ "$os" == "windows" ] && echo ".exe" || echo "")
          mkdir -p ./release/monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN
          cp ${{ env.SRCPATH }}/configuration.json ${{ env.SRCPATH }}/LICENSE ${{ env.SRCPATH }}/server.crt ${{ env.SRCPATH }}/server.key ${{ env.SRCPATH }}/README.md ${{ env.SRCPATH }}/cacert.pem ./release/monitoring-agent-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN/.
          
          pushd ${{ env.SRCPATH }}
          
          GO111MODULE=on GOOS=$os GOARCH=$arch go get ./...
          GO111MODULE=on GOOS=$os GOARCH=$arch go build -o ${{ env.SRCPATH }}/monitoring-agent-client$suffix
          popd
          cp ${{ env.SRCPATH }}/monitoring-agent-client$suffix ./release/monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN/monitoring-agent$suffix

      - id: upload-builds
        uses: actions/upload-artifact@v2
        with:
          name: "monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN"
          path: release/monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN/
          if-no-files-found: error
          
  upload-binary-release-assets:

    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [linux, windows, freebsd]
        arch: [386, amd64]

    runs-on: ubuntu-latest

    needs: [get-commit-sha]

    steps:

      - id: download-release-binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v2
        with:
          name: "monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN"

      - id: create-release-archive
        if: startsWith(github.ref, 'refs/tags/')
        run: tar cvzf ./monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN.tar.gz ./*

      - id: upload-binary-release-asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.make-release.outputs.release-upload-url }}
          asset_path: "./monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN.tar.gz"
          asset_name: "monitoring-agent-client-${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{needs.get-version-number.outputs.version}}-BIN.tar.gz"
          asset_content_type: application/octet-stream